package org.vaadin.miki.touchee.views.list;

import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.Set;

import org.vaadin.miki.touchee.views.ToucheeView;

import com.vaadin.addon.touchkit.ui.NavigationButton;
import com.vaadin.addon.touchkit.ui.Toolbar;
import com.vaadin.addon.touchkit.ui.VerticalComponentGroup;
import com.vaadin.data.Container;
import com.vaadin.data.Container.ItemSetChangeEvent;
import com.vaadin.data.Container.PropertySetChangeEvent;
import com.vaadin.data.Item;
import com.vaadin.data.Property;
import com.vaadin.event.Action;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Component;

/**
 * A view that lists all objects in a given container. Allows callbacks for selecting an item, adding and removing button clicks.
 *
 * @author miki
 *
 */
public class ListView extends ToucheeView implements Container.Editor {

  private static final long serialVersionUID = 20140925;

  /**
   * Action for selecting an item. This action is internally called by the view, do not add it.
   */
  public static final Action MARK_ITEM_ACTION = new Action("!Select");
  /**
   * Action for choosing an item. This action is internally called by the view, do not add it.
   */
  public static final Action CHOOSE_ITEM_ACTION = new Action("!Edit");

  private Container container;

  private boolean selectionAllowed = true;

  private ItemComponentGenerator itemComponentGenerator = new DefaultItemComponentGenerator();

  private final VerticalComponentGroup layout = new VerticalComponentGroup();

  private final Set<Object> selection = new LinkedHashSet<Object>();

  private final Container.ItemSetChangeListener itemListener = new Container.ItemSetChangeListener() {

    private static final long serialVersionUID = 20101003;

    @Override
    public void containerItemSetChange(ItemSetChangeEvent event) {
      rebuildList();
    }
  };

  private final Container.PropertySetChangeListener propertyListener = new Container.PropertySetChangeListener() {

    private static final long serialVersionUID = 20101003;

    @Override
    public void containerPropertySetChange(PropertySetChangeEvent event) {
      rebuildList();
    }
  };

  /**
   * Constructs the list.
   */
  public ListView() {
    super();

    this.setContent(this.layout);

  }

  @Override
  protected void onBecomingVisible() {
    super.onBecomingVisible();
    this.rebuildList();
  }

  /**
   * Rebuilds the list.
   */
  protected void rebuildList() {
    this.layout.removeAllComponents();

    if(this.container != null)
      for(Object itemId: this.container.getItemIds())
        this.layout.addComponent(this.getItemComponent(itemId, this.container.getItem(itemId)));
  }

  /**
   * Returns a component that represents an item. It is a checkbox for marking items, a real component as generated by {@link #getItemComponentGenerator()} and
   * a navigation button for choosing an item. Both checkbox and selection button initiate actions ({@link #MARK_ITEM_ACTION} and {@link #CHOOSE_ITEM_ACTION},
   * respectively). In both cases the target will be an item's id.
   * 
   * @param itemId
   *          Id of an item to generate component for.
   * @param item
   *          Item with the data.
   * @return A component that represents the item, together with action-related components.
   */
  protected Component getItemComponent(final Object itemId, final Item item) {
    Toolbar row = new Toolbar();

    if(this.isMarkingAllowed()) {
      CheckBox marked = new CheckBox();
      marked.setValue(this.selection.contains(itemId));
      marked.addValueChangeListener(new Property.ValueChangeListener() {

        private static final long serialVersionUID = 20140926;

        @Override
        public void valueChange(Property.ValueChangeEvent event) {
          boolean selected = (Boolean)event.getProperty().getValue();
          // update selection
          if(selected)
            ListView.this.selection.add(itemId);
          else ListView.this.selection.remove(itemId);

          ListView.this.handleAction(MARK_ITEM_ACTION, ListView.this, itemId);

        }
      });
      row.addComponent(marked);
    }

    Component main = this.getItemComponentGenerator().getComponent(itemId, item, false);
    main.setSizeFull();

    NavigationButton select = new NavigationButton();
    select.addClickListener(new NavigationButton.NavigationButtonClickListener() {

      private static final long serialVersionUID = 20140926;

      @Override
      public void buttonClick(NavigationButton.NavigationButtonClickEvent event) {

        ListView.this.handleAction(CHOOSE_ITEM_ACTION, ListView.this, itemId);
      }
    });

    row.addComponents(main, select);
    return row;
  }

  /**
   * Clears selection.
   */
  public void clearSelection() {

  }

  /**
   * Returns the set of currently selected item ids.
   * 
   * @return Currently selected item ids.
   */
  public Set<Object> getMarkedItems() {
    return Collections.unmodifiableSet(this.selection);
  }

  @Override
  public void setContainerDataSource(Container newDataSource) {
    // remove old listeners
    if(this.container != null) {
      if(this.container instanceof Container.ItemSetChangeNotifier)
        ((Container.ItemSetChangeNotifier)this.container).removeItemSetChangeListener(this.itemListener);
      if(this.container instanceof Container.PropertySetChangeNotifier)
        ((Container.PropertySetChangeNotifier)this.container).removePropertySetChangeListener(this.propertyListener);
    }

    this.container = newDataSource;

    // add listeners
    if(this.container != null) {
      if(this.container instanceof Container.ItemSetChangeNotifier)
        ((Container.ItemSetChangeNotifier)this.container).addItemSetChangeListener(this.itemListener);
      if(this.container instanceof Container.PropertySetChangeNotifier)
        ((Container.PropertySetChangeNotifier)this.container).addPropertySetChangeListener(this.propertyListener);

    }
    this.rebuildList();
  }

  @Override
  public Container getContainerDataSource() {
    return this.container;
  }

  /**
   * Returns currently used item component generator.
   * 
   * @return Currently used item component generator.
   */
  public ItemComponentGenerator getItemComponentGenerator() {
    return this.itemComponentGenerator;
  }

  /**
   * Sets the item component generator and rebuilds the list.
   * 
   * @param itemComponentGenerator
   *          New item component generator.
   */
  public void setItemComponentGenerator(ItemComponentGenerator itemComponentGenerator) {
    this.itemComponentGenerator = itemComponentGenerator;
    this.rebuildList();
  }

  @Override
  public Action[] getActions(Object target, Object sender) {
    if(this.getContainerDataSource() != null && this.getContainerDataSource().containsId(target))
      return new Action[]{MARK_ITEM_ACTION, CHOOSE_ITEM_ACTION};
    else return new Action[0];
  }

  /**
   * Checks whether marking items is allowed.
   * 
   * @return <b>true</b> when marking items is allowed (default), <b>false</b> otherwise.
   */
  public boolean isMarkingAllowed() {
    return selectionAllowed;
  }

  /**
   * Sets whether or not items can be marked. Rebuilds the list, does not clear the selection.
   * 
   * @param selectionAllowed
   *          Whether or not marking items is allowed.
   */
  public void setMarkingAllowed(boolean selectionAllowed) {
    this.selectionAllowed = selectionAllowed;
    this.rebuildList();
  }

}
